<a href="https://colab.research.google.com/github/JS-DS-coder/Algoritmos/blob/main/Copia_de_Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Laboratorio 1**

Ing. Jairo Salazar

In [ ]:
import numpy as np
import timeit

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b =  np.array([(1.5,2,3),(2.3,1,3)],dtype=float)
b

array([[1.5, 2. , 3. ],
       [2.3, 1. , 3. ]])

In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
d = np.arange(15000)
d

array([    0,     1,     2, ..., 14997, 14998, 14999])

El poder de PYTHON son las operaciones VECTORIZADAS

In [ ]:
# iterative sum
total = 0
for item in range(0, 15000):
    total += item
a = total
print("\n" + str(a))

print("Time taken by iterative sum : ", end = "")
%timeit a


112492500
Time taken by iterative sum : 33.6 ns ± 0.312 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [ ]:
# vectorized sum
print(np.sum(d))

print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(d)

112492500
Time taken by vectorized sum : 7.07 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**Operaciones vectorizadas**

In [ ]:
g = a + b
g

array([[2.5, 4. , 6. ],
       [3.3, 3. , 6. ]])

In [ ]:
h = a/b
h

array([[7.49950000e+07, 5.62462500e+07, 3.74975000e+07],
       [4.89097826e+07, 1.12492500e+08, 3.74975000e+07]])

In [ ]:
a==b
a<b

array([[ True,  True,  True],
       [ True, False,  True]])

In [ ]:
#comentario
a.sum()
a.min()
b.max(axis=0)
b.mean()
np.median(b)
np.corrcoef(a)
np.std(b)


0.7340905181848413

**IF THEN ELSE**

In [ ]:
edad_alumno = 15 #bloque1
edad_minima_votacion = 18 #bloque1

if edad_alumno >= edad_minima_votacion :

    print("El alumno puede votar") # bloque2
    print("Generar horario de votación") #bloque2
else:
    print("El alumno no puede votar") #bloque3

print("Esto no es parte del 'if' ni del 'else' y se ejecuta despues de estos bloques de código independientemente") #bloque4

El alumno no puede votar
Esto no es parte del 'if' ni del 'else' y se ejecuta despues de estos bloques de código independientemente


In [ ]:
x = 0.4
if   0 < x < 1:
    print("x se encuentra entre 0 y 1")

x se encuentra entre 0 y 1


In [ ]:
monto = 1000.00
pais = "HN"
interes = 0.0

if pais == "GT":
    interes = 0.1
elif pais == "ES":
    interes = 0.15
elif pais == "HN":
    interes = 0.05
elif pais == "NI":
    interes = 0.2
elif pais == "CR":
    interes = 0.07
elif pais == "PA":
    interes = 0.08
else:
    print("Alerta: Pais no valido :",pais)

#nuevo_monto = monto + (monto*interes)
monto += (monto * interes)
nuevo_monto = monto
print("Monto con intereses:",nuevo_monto)

Monto con intereses: 1050.0
